# -*- coding: utf-8 -*-
"""RC_StocksBot1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UDcXl5-Ofd1asQIUFhRi9_YO9omPyBQx

# Libraries
"""

import yfinance as yf
import pandas as pd
import matplotlib.pyplot as plt
import requests
import os
from datetime import datetime

"""# Fetch Live Data"""

tickers = ['NIFTYBEES.NS', 'GOLDBEES.NS', 'SILVERBEES.NS']
data = []

for ticker in tickers:
    ticker_obj = yf.Ticker(ticker)
    # Get today's current price
    price = ticker_obj.history(period='1d')['Close'].iloc[-1]
    name = ticker.replace('.NS', '')
    data.append({'ETF': name, 'Price (INR)': round(price, 2)})

df = pd.DataFrame(data)
df.head()

"""# Plot"""

plt.figure(figsize=(8, 5))
bars = plt.bar(df['ETF'], df['Price (INR)'], color=['#4C72B0', '#E1B31E', '#C0C0C0'])
plt.title(f'Live BEES Prices - {datetime.now().strftime("%Y-%m-%d")}')
plt.ylabel('Price in ₹ (INR)')

# Add price labels on top of bars
for bar in bars:
    yval = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2, yval + 1, f'₹{yval}', ha='center', va='bottom')

plt.savefig('chart.png')

"""# Message"""

# Format the Table Message
message = "📊 *Live Market Update*\n\n"
for index, row in df.iterrows():
    message += f"• **{row['ETF']}**: ₹{row['Price (INR)']}\n"

"""# Telegram Bot"""

# 3. Send to Mobile via Telegram
TELEGRAM_BOT_TOKEN = os.environ.get('TELEGRAM_BOT_TOKEN')
TELEGRAM_CHAT_ID = os.environ.get('TELEGRAM_CHAT_ID')

# API Calls to Telegram
base_url = f"https://api.telegram.org/bot{TELEGRAM_BOT_TOKEN}"
requests.post(f"{base_url}/sendMessage", data={'chat_id': TELEGRAM_CHAT_ID, 'text': message, 'parse_mode': 'Markdown'})

with open('chart.png', 'rb') as photo:
    requests.post(f"{base_url}/sendPhoto", data={'chat_id': TELEGRAM_CHAT_ID}, files={'photo': photo})
